### ISSUE TITLE
R-T3.4-13: The radon-repositories-collector must allow users to filter projects

### ISSUE THREAD

**Issue by dardin88** [radon-h2020/radon-repositories-collector#2]
ID | R-T3.4-13
-- | --
Section | WP3: Methodology and Quality Assurance Requirements
Type | FUNCTIONAL_SUITABILITY
User Story | As an Operations Engineer/QoS Engineer/Release Manager, I want to crawl software projects that meet specific criteria
Requirement | The radon-repositories-collector must have a filter to crawl only software repositories that meet certain criteria such as the minimum number of stars, the minimum number of issues, the minimum number of watchers, and the minimum number of releases
Priority | Must have
Affected Tools | DEFECT_PRED_TOOL
Means of Verification | Direct implementation on IDE, feature checklist, case-study

**Comment by stefanodallapalma** [comment]
From commit 7fc139654ce1d269137b0476c9654f3e4331fc9e it is possible to filter repositories by:

* minimum number of issues;
* minimum number of releases;
* minimum number of stars;
* minimum number of watchers;
